### PR TITLE
Move logging code into own module

### PR DESCRIPTION
**Pull request by MrCreosote**
for reuse

### CODE REVIEW

**Comment by jayrbolton** [comment]
Looks like that LGTM gremlin is complaining about something, trying to see why.

**Comment by MrCreosote** [comment]
Looking at the lgtm logs there's nothing obvious

**Comment by MrCreosote** [comment]
```
Running: java -Xmx6G -jar lgtm-worker-tools.jar prPollGit --base-sha 1c49aa9bb12a909f5c68520cf8033ecae804b2b8 --base-remote https://github.com/kbase/index_runner_deluxe.git --main-bundles main_bundles --incremental-bundles incremental_bundles --head-sha f21ab16d8fbf6de479c742c7a94b6dfc8fad83fc --extra-base-refs pull/130/head
```

is the last entry

**Comment by jayrbolton** [comment]
Okay, LGTM

**Pull request merged**
